### ISSUE TITLE
Considering adapting the code to XrmToolBox plugin?

### ISSUE THREAD

**Issue by MscrmTools** [NZxRMGuy/crm-documentextractor#2]
Hi @NZxRMGuy , the tool is super useful but not user friendly

Would you consider adapting it as a XrmToolBox plugin? if not, may I?

**Comment by NZxRMGuy** [comment]
Hi Tanguy, sure go for it :)

**Comment by MscrmTools** [comment]
Cool! I will do it and mention the code comes from you

**Comment by MscrmTools** [comment]
Done!

Here is the [repository](https://github.com/MscrmTools/MscrmTools.DocumentTemplatesMover)

Also available in the Plugins Store of XrmToolBox

**Comment by NZxRMGuy** [comment]
Wow you are quick! nice work!
